international_showtimes:
  base_url: 'https://api.internationalshowtimes.com/v4/'
  api_key: 'QjXKnthSninXnFdJYWNG56TjYXZr17Jk'
tmdb:
  base_url: 'https://api.themoviedb.org/3/'
  api_key: '7c1109395352e900ae045c434aedce0f'
